DRAFT WebRTC Protobuf Update
refraction-networking/gotapdance pull request #76
Opened 2021-10-09 23:48 UTC by Gaukas

Adding WebRTC-related fields to protobuf. Changes are not final.

2021-11-01 00:54 UTC, Gaukas reviewed
- Added webrtc capability to shared code.
- Modified Protobuf to support webrtc.

2021-12-08 00:17 UTC, ewust requested changes
Let's trim this down to just the protobuf changes for now, and leave the TODOs/active dev stuff on a branch.

2021-12-08 00:17 UTC, ewust commented on protobuf/signalling.proto
> +    optional string shared_secret = 2;
We should probably not send the shared secret in the clear like that, no? Is this derived from the seed? If so, then no need to send it in this protobuf

2021-12-08 00:17 UTC, ewust commented on tapdance/conjure.go
> +	// TODO: WebRTC Init Connection and get LocalSDP, send with Register()
Probably should not merge this whole PR until we have the rest completed; we can merge the protobuf things separately for now

2021-12-28 07:29 UTC, closed without merging